steps:
  - group: "a group"
    notify:
      - github_commit_status:
          context: "custom-context"
    steps:
      - label: "pass"
        commands: "true"

      - label: "fail"
        commands: "false"
        soft_fail: "true"

